name: Build TrollInstallerX

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'TrollInstallerX/**'
      - '.github/workflows/build-installerx.yml'

defaults:
  run:
    working-directory: TrollInstallerX

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ldid
        run: brew install ldid

      - name: Build IPA
        run: |
          xcodebuild -configuration Release -derivedDataPath DerivedData/TrollInstallerX -destination 'generic/platform=iOS' -scheme TrollInstallerX CODE_SIGNING_ALLOWED="NO" CODE_SIGNING_REQUIRED="NO" CODE_SIGN_IDENTITY=""
          cp Resources/ents.plist DerivedData/TrollInstallerX/Build/Products/Release-iphoneos/
          cd DerivedData/TrollInstallerX/Build/Products/Release-iphoneos
          mkdir Payload
          cp -r TrollInstallerX.app Payload
          ldid -Sents.plist Payload/TrollInstallerX.app
          zip -qry TrollInstallerX.ipa Payload
          cp TrollInstallerX.ipa "$GITHUB_WORKSPACE/TrollInstallerX/"

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: TrollInstallerX-ipa
          path: TrollInstallerX/TrollInstallerX.ipa
